- name: Run TFC project listing
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List projects in HCP
      hashicorp.tfc.projects_info:
        token: "{{ token }}"
        hostname: "{{ hostname }}"
        organization: "{{ org }}"
      register: output

    - name: Show projects
      debug:
        var: output.projects
